// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63c0b0f3e696197ddb44ac96
###
GET http://localhost:3000/contacts/63c0b0f3e696197ddb44ac97
###
GET http://localhost:3000/contacts/63c0b0f3e696197ddb44ac98

// PRODUCTION Deploy
###
GET https://api-64im.onrender.com/contacts
###
GET https://api-64im.onrender.com/contacts/63c0b0f3e696197ddb44ac96
###
GET https://api-64im.onrender.com/contacts/63c0b0f3e696197ddb44ac97
###
GET https://api-64im.onrender.com/contacts/63c0b0f3e696197ddb44ac98




### ----------------------------------------------------



### Create NEW USER
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{ 
    "firstName":"Mary2",
    "lastName":"Star",
    "email":"mstar@test1.com",
    "favoriteColor":"Pink",
    "birthday":"16/02/2000"
}

### PUT contact 
PUT http://localhost:3000/contacts/63c9cf0c51057c694b6e4c85 HTTP/1.1
content-type: application/json

{
    "firstName":"Dale2",
    "lastName":"Anderson2", 
    "email":"danderson@test.com", 
    "favoriteColor":"Yellow", 
    "birthday":"02/24/91"
}


### DELETE contact 
DELETE http://localhost:3000/contacts/63c733e38efe6c93f4d43f47 HTTP/1.1


------------------------------

### Create NEW USER
POST http://api-64im.onrender.com/contacts HTTP/1.1
content-type: application/json

{ 
    "firstName":"Mary2",
    "lastName":"Star",
    "email":"mstar@test1.com",
    "favoriteColor":"Pink",
    "birthday":"16/02/2000"
}

### PUT contact 
PUT http://api-64im.onrender.com/contacts/63c9cf0c51057c694b6e4c85 HTTP/1.1
content-type: application/json

{
    "firstName":"Dale2",
    "lastName":"Anderson2", 
    "email":"danderson@test.com", 
    "favoriteColor":"Yellow", 
    "birthday":"02/24/91"
}


### DELETE contact 
DELETE http://api-64im.onrender.com/contacts/63c733e38efe6c93f4d43f47 HTTP/1.1
